application.version=@appVersion@
debug=false
server.port=8100
server.tomcat.max-threads=10
#server.tomcat.max-connections=100000

# Keycloak settings
spring.security.oauth2.resourceserver.jwt.issuer-uri =${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

